#!/bin/bash

message () {
    echo ""
    echo "usage: tl-switch yes [year]"
    echo "       tl-switch no"
    echo ""
    echo "       [year] is optional, with the form 20XX."
    echo "       It defaults to 2019. Thus:"
    echo "           \"tl-switch yes\""
    echo "       is the same as"
    echo "           \"tl-switch yes 2019\""
    echo ""
    echo "This script is used to switch between vanilla TeXLive and the"
    echo "version of TeXLive installed on a system like Debian, Ubuntu,"
    echo "Mint, etc. See the README.md file for installation."
    exit 1
}

if [ -e "/opt/tex/$USER" ]
then
    echo "Context switch path exists: /opt/tex/$USER"
else
    echo "You have not set up the ability to switch contexts."
    message
fi

if [ -z "$2" ]
then
    year="2019"
else
    year="$2"
fi

if [ "$1" = "yes" ]
then
    if [ -d "/usr/local/texlive/$year/bin/i386-linux" ]
    then
        target="/usr/local/texlive/$year/bin/i386-linux"
    elif [ -d "/usr/local/texlive/$year/bin/x86_64-linux" ]
    then
        target="/usr/local/texlive/$year/bin/x86_64-linux"
    else
        echo "Target directory does not exist."
        message
    fi
fi

if [ "$1" = "yes" ]
then
    if [ -e "/opt/tex/$USER/bin" ]
    then
        rm "/opt/tex/$USER/bin"
        ln -s "$target" "/opt/tex/$USER/bin"
        echo "Resetting /opt/tex/$USER/bin to target:"
        echo "$target"
    else
        ln -s "$target" "/opt/tex/$USER/bin"
        echo "Setting /opt/tex/$USER/bin to target:"
        echo "$target"
    fi
elif [ "$1" = "no" ]
then
    rm "/opt/tex/$USER/bin"
    echo "Removing path: /opt/tex/$USER/bin"
    echo "System default TeXLive is now used."
else
    message
fi
